[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "6dbb9f79208a887a1848de4982c963572a1b9b33e9a59bfdae7b1bd260381b43"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-v1.0.14-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "506f32bf7927376ae6b313232aa4313f645bb4e6"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "47c620d9b5af6e11673e46a32a0a27e69b700755bdf8c9558410c6aabdec8e15"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-build_log-v1.0.14-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "59a00b19e1e6ee4a7f1288dfbd6ab59612ff4746"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e3d4afc9d7bd0dd594649e0cf483cc76977c33e6f40cec202b6be5f9fe80a4b9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-extract_log-v1.0.14-x86_64-linux-gnu.tar.gz"
