[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4ab2a1301e0582401b3ad4aa08bae9f776c547da242b2452e50f075b2300a598"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.10-GCCBoostrap/Zlib-v1.0.10-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "4cca5ded06a4911fe6688f8dd17b270066e42d4c"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3fb662ea50a3a6fcc8aa147e29d6b4bd2779e2617c1ac3c84eb30eaf2fb92f57"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.10-GCCBoostrap/Zlib-build_log-v1.0.10-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5238196b550f6864226a859f8eb58d05252a92bb"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e6e6570a494462963d09fd793da79147e3e6823f258a44298f0e55bc536cc0a3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.10-GCCBoostrap/Zlib-extract_log-v1.0.10-x86_64-linux-gnu.tar.gz"
