[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "83ac2be068323c649a5f60aa58afac58f4ee0eee7dd97564a8c86351ce8ae9b9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "1cef59d581c126ae8f415d55bdf2620e9cdfa4058f1a30f7b9740342bd951284"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "bd0c24970892cc700edf758f359c98ba1ee0738627b350ffe117bf5775912a20"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "290f4efb4fd00c2b928fb3564bc4844eba8efefd37b8bac710a772f2a025bd86"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "a42af3c59db02229392d3b112a19eb1588e290431a4bb67c928109512c388eca"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5c5aa737adad51ad57032a5fae488973e0eb1aff7d5444898c0d95c478279ba0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "93983961cae60fa5fb055b629fbde4464168ff86371393f70c52d045b52c9b6a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "deea3de1a9e2480dcab08a3362796565b623ac728113f66b2d864af3a5d15621"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "192b3e257f676b9c4011ac64c86d22f44ba6f236b09d494da2b410a3e5da5b2d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "349912e6994a987e0aa0d7660582af843baf6b6172f8339dc237cf2185de530c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "14f6e807adbb12e5fd72d978179da9cf0df473639051b966e3c8521f6693e4a3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "6b492611def6aafb10891e470d3007c531aec2b44b761a475a6985f1b518d3f5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "e6d0f3e1509b9f762b2e34d0f0a8c6f774fc7d518258261c70e9248e724e0442"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-v1.3.5-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "27a75a4083e812b60c5776398ec0c986af598c9d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5ec4cbd36168d697fcce3f2a376ce530e0b224a8defe3dcf8e3a332374a7e29f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "50757943b57d6e37a16adc43e5ec5abd97ddb066"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3b6293bcd562123819e06b365326f225439afa19cd139ba0cc6915b801af692b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "07188adcc4765cf891650f3c3648972de1b8da22"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ec9808754b8cdaceea8206323bbf273336ae872fbcc9f59c358f65b0ca3b09bf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac0b4fde779e1dd84d7f590f89f2847366c0c470"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1132da46d58c2a82a885a34892baaa767ddd95aa9df2179d4dc8be4f111a8b2e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce1ec16f0976b5be22727b8be70b1abece3445ce"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1d1d6db8a28537218bfbf430515a247f7eeda292aae915688aa378f14314d7e0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "9fb0efa7535e586a72c6077e7fa060ad5794f54a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "724d47837f615afec1961bb786a64e8bcbaadbe0f83c429205066895dd8b906a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "6263919deebfd7b4fb28f3b594a46310af8ec238"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "cbebd1a387f1a64086cd9eb9d1df3667dad14d4b27af38e8fa098a898aa5e156"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "6dbe3fb87e22d692fa90fd224bcf55fd34430238"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "cf0d6c4d2752e1104ced801296b0a82be58035e1fb9f6c2ce1561be3be2764ec"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "89afc28151940b5c883c8954693b23991dae6c7a"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "71b3ccaf6eb8e1da463d8981b167c20374934c0f628fee1e747176160fe901ca"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d6302c4448ff7aa47bdb1f9326a9251a9d71b04"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "de1d27d359f90de3b93200b935f92c60b0b40b4fbe4ec34882d99f79db3ccd74"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04e3db497ca73ebe3fc668810b74aeecfcab4621"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5df38006107647a866fe2e3c76022ab3e3bd28a89ea99c7dda27716cb50c07f5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "e9526f683822c7270ec50412a663f388b34f6fe0"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "909ef646e2e0d14b31604876a71185f222830ffc60199d2e85bdc0e0c1b66061"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "e2d1de85eb8e9e2a0c08af58a81dc66415330a62"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "163aa5be5484220b428a8c14615bd9a512da0067edfb22f7de3b930010176d4c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-build_log-v1.3.5-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ae6a743e9782d893894f44f7d5d0d0e330102b25"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b7233e4de2393f2bd2ac28ff47b6621bd4789af67dbea135bf044629d7ed937d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "a1c8593015d001b2449d9b2e3cc772e8fd097dd9"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "6e188336792ca5086b9a34910fbb085fadd151c019d1c3abdca5475c1fb33a18"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "18334697eb843735f370e8dc583ba438c7cd7984"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "2126dd9121957a0325b98472787e034595b858be0e012a1d0324e44a203bef77"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36c3cb5840e55707d0d7232da1e770cd40a4aa48"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "7557df61082111b3a0b65ca0e40b683b8bdda1c4b13e8e88c44d346b3749e87b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fef07c2459a784d80cec5f06b6177d085a0879ea"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "2215e1651efc120b08cb49053da5d974f137f1c6e767c634c2b860d7f5c49810"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "1e414af0e5e721e44c96971ac20dc0860bad96f7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "9906fe0fcefbb9af153a804b8656110fec5a9640ab4e9e89e16893bc8a889d1e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1d878a8db47f8225cb9e83f5c334084758d0e212"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ab18417d7fff569512ce42f4d012bbae5ca53990cbe092ed7f57bbbbfcbf6cf1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "de05e1bbff61b1cda34cf415a5e3bff3b026be50"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d21c4d6146af27496d4d9e4101dcf38f9c034414994a78db0369feac1d646147"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f590bcd70d98d139af8fac53c493b0edfd44e340"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c6d8514eb771fb9f81cb77739ad89dc059ac93ca7eee0bba1ed4381cd236c7cd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56cd042bb14dc51a30ffa08e34479fca82e36e24"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "5e506d4ec2ea88afdbc53521fae037d51ee3ea904514207e2ce58f6979571785"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f67a5c4f232a9791199c2c0543f60b32f2c309d2"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f2251dcaaa04aac76426706b5568c948dde14b6491715acabc1c79a4fa8daf5d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "36174e3e566df0d05a73f7ae40bdb329d0564c84"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "443206ec6babe95fe38f77b272c91004b1ac7e921bb20b4909247c30c0df8dec"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "7927ee701a71f6e3c54a02aab29d9b7999a030f7"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "19306c130790b86da657e628e0b31594195c1eb532a41c7d16a29d8f154b2581"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.5-universe_test/Zlib-extract_log-v1.3.5-i686-w64-mingw32.tar.gz"
