[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "8b4cd5b1998dc2b1a87ab2c1a0442bad1c120c5262629542f6bdc4832cbc243f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4fbb1d80a385a230bdabaaf988917d0c2698d22edcc0a8b6d348b631f4363c14"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c7fbacbb6219725c7b93d04f8276431c81ba45aa76f5e3aa9460f3a1992e7b81"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4202e054d93364c6ab01766eee027905132a130b4da7ea06d2d5ca50206ce1c3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c06a2765945e92fad7fa5a7e434c43ffc3dcea0801bada1ec1a8db8f8d9af392"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "87650a98cf91eebad4afd9b04c873ee540d2e057c5fac05c3ca726fa38cacabf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6413bc105ae9536ed8c81cb8a0dc399f0e8bc9d325ecd2a88386ca2cb0c81a93"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6dba59b0e1552656ce49c463b8a24251817249bdeb85c7b216ee101963cc5320"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "906a4dda9ac41cc11b87c107481d0255d1d86a76a1a2b4bb8ea3439747de21d7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "b13487ffbca0a00d95e7208fd96cdafdcbe212b0d9c06c77ff93edac7f832f16"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "543bce151f21c6227b353149d1d6fd5ea346dca0b943468f65fee2524c6b7b63"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "eec9fbf6487dba8e56050af187356752c65efd372d40b6f78c65c7712f6b548c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "90f2f13c27c972b431507f554c13c5e0bea6c1faa29a9ca189fca8c6c12993ed"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-v1.3.3-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "f8ba4fd3051e14818a4236114a0422d1cf469d1a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "385f7e93ddf2f8b4ec94bbd5a2ffa211bc16cf77f72ebdac8376a9c0ec0d4fb1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "1d66e4628cb45fa8e5f98e82f1267a876394f751"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "af0953a0b768600e55204f5f497e1a35f304bf340c1dd08d0a643c67c5f04e7d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "cf52475a6bfe620c15fb7fb5a2e29e054a80d450"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "06531b21ade63051c1da7e2a961a9a6f2945daeadcc82a1fbe09c7963c892d02"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b786c0511135861f44a502c0445cdb0b2ecd4801"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "eed34066b6bcd675f6efd0e0a0ffcaa669189b32975ba3e22cbc4cc393786d18"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83fb9cd57ae211abaf7f712313fd1b912f8206de"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "54718e4c6de86ff8d683d8f0c782a66c7cbe9f4b277a59be9930bea468896131"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "23c4794c18ab2e0f260e8b2e3498caa21e8c8ce8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f3bf1557bce4ff9f537c3b472a557a986134bfbad46ed27918f07de8aae2bdd7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "ed5b21abb6d43a2b02929eefd254498b3f0c221e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "15fce82eb52ab1f39a13e0911bf8040c9197dbc0be981d780374fc4c6620c110"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "67cf9329a6a2bcb70b9921bba1bacda11ad5d8c2"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3f7beaf1f71f436b7568cba4ffc4e21802756874ee35ba3a026d407439fefd08"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "aa938edd0bd38fe82ab521f61d53dbaed87a2e99"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f29ddce3f4d135c0e63d5a6585eba649f1fc7f882b705a7e7e17766199fd6ffb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1092679d02955dbcccfe31a30792b935f804b1e7"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3b5c682eb04ed21addc2391866e37682b2fb365cbee530af0feb96468476db2d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71169bc821af633f57d4b20d8c6c6cf91cab88ed"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3cbdd7d514aca0b6faf493fa8c1a1e2d81add940c29cdc7f7a7066304819bfd2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "08cc9442ebc79b2cca840101aa30963b253a7a32"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "35f3ec9c56e375638a9b5fabf000643db6abf3f052947051407513706f9a78d1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "8a4ef92041545e61dcdd563175f9d8a07a38a35a"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "09db0a909196b7b08c897b4e6353140b84894cd18daed40dd2caaad7fa6ed01c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-build_log-v1.3.3-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ff869522b2e45ab7893522e7064b76fba278506d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "39a2e9201a4c6083dd544a23b153435967ec4e5340179beded7e0ed9b7628cf1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "b1264bafc3fb6fbe165e6cff303463e4d4014984"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d8fa9a876e80754111675462d59f4ae1e1c739cc4444b36bdc12927e0d0c7631"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5246c42c3666f7b8219fdbe71e6db9917a2aeba7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ad6a4f708c58c8aa2b5a48261a18f35c9b28db3d0fb76153797283156bebbd4f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cdd33778f3ffa71d4cdb457651fc32703fd956e4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e4ee9667633de47279aa2c6b73a3043eaeea7dd9e3c09da6b9764b00b7702254"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7d2a21dd82f69a175d5c93a70f03c50a77f7400"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "712749b7efc6c7aa817814a667431d928e8295d6c14c3e650abcd981df4c9def"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "2b600d6539da8722da5bcccf456c180c47beeb92"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "26d1383181e39bfc906577e3f4a97c82875eb0ed2c54916111c2feebcb2a9b66"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "648f42e1668b6fc4bebb3bc47a48cea9dcc75ef9"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ca3f41f189df5b45f812b3809911ae3b53dd9488cfa2defbd54adf94cc5637a9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "ef82f04997cd4d1823ad1c693941473fe9ceb6ee"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b950fab16611af9347ab536dd010a0581c91aefb2ee643e62de119cec089793a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f20c9983d59b37fb07c2b023507576a2d38774fd"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "2508e2cf511a6deb7b6ac5337402ef14c1f8099c65bc5ab4eb349fef0b55e748"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "814740592d661ac2d508d89001e837879866726f"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "764cd62b806b08fc9eee6eceb49ae656446b56f77b7d4e3750aa21aa3801b35f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87cf46f8a72a302fc6c9128aa45094ca4b7a6527"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "74dbdce87dbbf1d5a3e9eaf79907089ebd56e1aa50fa4d1e0ac2088775b5cfc0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e1cd68adaa30cd416c6252eb31b18282012cae93"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "2f6248532291d4685f5d060aefd7f032260a659e3abc6df66f00eccd9d17ac38"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "f3afdb2c2ec3f1fd911738c91be0e7423f3176b4"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "c173a2c6873efb76b91ff8ca79a39b4c6712049db2f9d5573adce3f9646e2719"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-universe_test/Zlib-extract_log-v1.3.3-i686-w64-mingw32.tar.gz"
