[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "867861eef4edfd96cd1877e3c6eb39259204342a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "a65d37a7adfcc6efd065f4f4a2738a50f0d1139a83d5064fb59196b890001a5c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "df9df56258644971695cba2820f213c5ad66bb7e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "fec3f83ff53bcf3c6696a416a4653cf48d4885274d2a70cfdb0a9efd1bdd74e7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "06b05d63273b2cf5c4e0395c7f88317f1389217a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "05e7d47d0fc5b2ee7ba93545f28348b27f1ec1df65c4873ffff2a56ae67756e1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
