[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "81498d5c4e4f2f8088e82a912a12d6956673abaa9c5f55307ae799a1fad1c807"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "856ff1ea98883fb95b23c7b06ea86c046d72f0a1627cdfaaa53f715278300d39"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "33c62a44bb26ee2ab69eb21f83d106e2f360d5d9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7ed0f7b7300bca7540e56b954dda4db436e060b17e8f3a0716e4945979e5d04e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c18b551896ae2d80072431b1148a0f6e5f388316405b67ee0de80fa913cf5fd8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "bf456e878b40673db99294afa6dd78853020c68cc26912ccaf82df96d04ccf11"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "af6fb29d3260792c33f028a874d71f5e123f6ab3c8e6b60922179f233f7d9a75"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "052647d3b9d8a32ac9f8e5b947bcb87731d31d85c18a190323b1fc8adfebbdc4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0bb16e427fe0b14822e930ef1336cd8dd6c69ba63991deb13604088f3383a243"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "a568fa10dcbf94a74be35d18425531753bb0887f0049c7970f82fb82dac7a3bd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "42c073279e12dbc5a5db7d44d61a6bd8361ffaa90d436fad1b1cd02743c82be1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9f369a5ff292d9ca6b2b620b4906314fe6a92e7537e3723728fae6634ddd2043"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "55c1f949c66bcdee3adde1d7981a3c8910a3dccb7299d056c669e73009ce32ba"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "af06592d08e8138232f1e2841126ff33d14737a451500445c8b0a9a01f3ffdbb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "2b4d1323c0702824aefd55bfbb970908793259b2"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "46377376df09cf15ec7dce1848b8df519626ad5d14d3499ea2ec67edbe42b139"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "74b94334c2f5c74994737340482544a7c2ffdb3a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "39bbe9dcac55eaed1043f1392d2239cfdf8dd2d4f20a1eee69c58a5bce3a2e1e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "707cdee1c85cc2b460d4952918536a712944daf8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1633fb4ff07392e2432f4ce48e815a1da7a2c1cabd84993f7974d0e793162717"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c026bd382c813a02f8f621ba690fbb87319a55bf"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1c655d9038afc705f0e27cd35083e120064a214fcf6d01ebf72335c02ddd4f55"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e2c3442a60a9c50858864777f0d870d354e7902"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "516f9a09e14795bba6ce29527c3d3b266e53ead3c0d29a5576446ab1d5831920"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "e5a62807f9aa95af5e5007745093da3c3b0e420a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "8ba51a01488caffe57f32af103075496fac2b30179ae413c30a05716b8617b81"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "869944b3d9080f89c2ca017a333a66faa309259c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "c2cb960c2848c6449a7dae4f413b7c365efa377791d342670feec62ddf9990f9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "ea7ad5ae75df5f27309bad4f2e2d8185b8b2e6bc"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d3e7231627f8acc38f351ff2e47bfe2ce2e80fd96651fb8e0e817228d24fc0b8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "8cf197efd6ca60e32b04b3511c4836849fd1c174"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "e723db690a2cc866aeec3924625851634458ba151987333da722af57ab03ef07"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89dcf2dce860675e316e673b2d0cd76e19e1e28c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "035b6d61d0a782a5f5ce39933fa64b107ed666258e207953d372ff4771fe428a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34b81e1d2477819f021e71dd466af69665ec07a3"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "800f1c351c34125c12b25f2d55cdb975bdeae1a31a1957ca2e4caa6225993216"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "703f857eb025a27744e019f676e8fc15f8985d3d"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "823f0bf439c0c36309954651aef2c2ea5dd33cb47b124ccd97ff6f9b9835d4bf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "e85be19fe19d1e3c83929afea7f545d7bd1d28da"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "586dc2cd0fab2fface26ddb274090e190bfed14b94de571c5db37cf5e1d33359"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2d36ffd36abc511142f43a3fab97ea4d8e573b10"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "15e817c749ae1c178f804426b61b76a29a5b33a008c0d21c6357bda7c99166e8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "3389487593098e59cb7a62e12918811ba7805c37"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "2a70089d11fe41c6e62231733e3f8df717507a312ff2ddc21e9b7248ecf288b3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "0e2dbc0c29ef752959c31cb68901f748bbb5083f"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "46cdf1f3735c954a4e56c0e7a39aaa2d140a4b319cd7e67239196e47f5b1a00d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "10675fff260dbc2de898039c7a13fa217a92e6a3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "96e4f09913ea5fce84d04cf9fc87472c267eed2b788bc358b87d5ce85a531536"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a14da9581580e9d72945432ea54c3310fba9db3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "84b0aed5b1afea2ddf9456bfdd2fad9445ad3effde22f739a63fedee533e5852"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "b71c3d29f621a961ea44b22e6bbcedb7756f1908"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f6612d357e6f9ba421b18188f43a78db6bf167a519d47d7baa4d0727e3f84000"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "443afd6f9b6179160601fea46ef87fb22536cb53"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f33193a2514efeec9e55332d7d79e7c4e7c9ccd682aeed66dc32cd83503d9f89"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "f55cf6d2e25e46593546847b97023161dd8d1b3d"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "a61108a77518fc73aa27fee216914c439180195e508437687d7a5401fd4c8324"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5b4e5699055ff4c66fa41ad186027cd37f927216"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d930bac8c09a131e26665216d333f37379c34391720f04e1cb71cd28255eb455"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "882193796afda54a1141c29161077bd67b214e7e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "6025384f4b287b47e67bdd97a85c4b6d530576ea14b07cc32343d829e51b0686"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e3bbba4e0f7db55319ee4e0eeb867645b633be22"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "abba7a8f4cb3abf2f573a038bd9d3fe410fb9306090aac9c0fd4f7da558dc904"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0db467116e5976cba4cfc2281cf73c83cb8511e7"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "4205dd795ff6b032e0b34ad9a1d32c0cc74c003cfa9e06be4f25d6afe5f1773c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "a3776938b240cc46c77ae0a94c38e0a01e956eac"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "3438df13fb7bf015155ffd3a37aa8e94f7d911a054e2e3090d926bf8a8c1bbe1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCC/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
