[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "24fe44bd280b86c076f8fa3991318471c36abb9b8d19bb5f46d3f8f30d3594fd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "8bed1b9b1287636cb14fc474b9ffcbd392d0d1a250a8fd1063809996cab004d9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "273a2bea67131cfea2f10c567779b2f1e30c036e7c0b50cba9f59f8a7c978696"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "f28200724bb850cc2384bda21d1bacca1335269d7a2cd4fd33e8df8447085f00"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7816227feb7cacb19395849279d3c8683d620e4fb0f5ce0b16e924dc890108c2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d17b33cbdad57716a2bc1bce5bcbc60832636bf4aada6226fd614a348e106dff"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "5efb591750a534ced7b99c966cbd1362d253274b35b510817ae79ccb693c383d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ea673b8b7cbaadcb5d2369dd59d33163eb87bb4ea6859436290ed5c22a538ae9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "1d0735af2570f526fc5664655a47feb29c3bae977d2987de166a1a2b07f6dfd7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9559928e2c3e5c4e6d8c3934ae114cef9ba9ef859da18266d821c7512deb9403"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "1dfab3fca85a059bc2a8a42c1bb7b1849e767251d606523bf729f02993f15e10"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "83309b1a99681d33247e322361f484f1f838bf0818ce0ec74aac56fcb168375d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "ce3570c636bcd51904e37d1261bfae075251996212df57f073ac0e6abdc4fc92"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "0f9ec0c78d214b8413951d6ed9e0df7c2fb7a076"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "916d5d47b446f5fc346b2057bf16389f50ae7330bd640348447bda7e11624846"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "92ebadfb87a8688d7ceb53df7d5badaaab4610f5"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "7c353ea7fe64c24ef1d3ee2cef3cc758a68440d169f42656bdc38d5d7417a42a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "2251d96246fd8654bd8b0b6e4dfc9d8668a9ff29"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "e67f732b598a703cc35959b84ab7b0041e6b2ff5fb73a60fd92c2108d16f556d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "07ec62646fff4e5b78dd47f1fe97b50f23a431f6"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "4a99017a507d0fe262e707e2ce88b55ba7ef2a95ba694d974ec1272795954a87"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6be4d4a92fb9040c9f8e0bbd89f873aef8c60c35"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5756002ac737c67f39ba69f280dbb1f84ab02eeef40feeace903f92be58adc26"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "0cece2127fe00f5bd3e823efa37582a5d6a1a5a8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "067f34a5f40bd89fa3d99ca9ac1ae3bfc13220fd5d5bca4f668f755cf151c71c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "1bfe210ba106445d534890946cb410f81902a0ab"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "e8f8db7ba6532bf5222e9f85c862abf2f0702edec24a18089e095593ac00253a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "0fd7dc24ee27884797ab1588551c8b14f8e6c62d"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "c6f277b2bfab2e1f0f8c5e8c0887f10c8d5294025b0cecf0d4ac8f7dbe7d919c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "ced6e3a7759e7c7e455e9517108ab7eb32b73869"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "52919ef7002f8fb22ae251d2a1802bf574089c07169529c9d2cf8dd8afa9a140"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "552338a952981a36e71c325b3c08ea4b37ecb228"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5a7f4898e52758c7ced143f08e91999bb7a4c84ec8d3c7df1280d7de715f757e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba33297b035b915c8e2336dd9ff8ca9717c74b4c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "6abeb08671fccb9a5a3f5ebdcc87a3fed87a0c1de7861fb53b0cb2eacc467ea8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "ee23f6dec6003f1287931afa8a40e6eb031705b0"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "3d75ed5c70cb9f99ef768cf6c458aaf6ca1378a063a3528863c05a0ae8bf7234"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "5d7f44cdb413e2b8a4ffd1415791744f37574654"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "e4e1e4d98b51b5a5fbbbf0ebec25ca03f952e4a12f92c9ee24c97b43cb71e68f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "34540d2ea91bbbe1cbc095544ff8ab78ae2bd214"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "30e6fe26908989c657a34b9d390d7989ebfbd87e98abdaced11344de4678af9e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "cfce1faa301c477728c2b470668929dac4042864"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d361e7d938db1c9f1a1a3eeb7268fa3780a028d3a506b3e9f53137f3f27438b1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "24fdde75875701d85dbf11a40bff300a7478ebdb"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "fddd595f836f58e876109c303ca1a53475760d9dd9edaab75fc7343e3ab3cfb6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a37e656c04037e01e0aa6f06dd4074fe531a1058"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "9ad8d07a6565c9173d655386b4e8ee5f5322145d026659676826cb11fe434f04"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cd56e3e83f5126a3188e486c11d3e4efc272ef4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "856e5f7a02b879b27362d53351f91c1e402497d3c317c8461849a2ad8d4a6a5f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "34d44df5aa7f875fe085749e5a924ad0f1b84f5c"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "5399609466f8cf4d60bdddd6f453c3e1c71902f452d8b8e1902bb77263cefe75"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "de4e382c31a34596ebe915603bdfcfc9fc51ba79"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "3eb35481f709c3c47b0d3b253b75cf6ec685a16ecbe07b47f9722fd45d8d612c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "04a2b55198d81f128f388c55fb200209ae8d6403"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f17a9832e9411f967bbf0e582d02a113d122890141303bab6b861373a070d102"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "374cfb19d33ed3803af0df3f5af0c989510be3c2"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "6d0a7afd9475c3f63a32e445e10de018a4498be5ec7f618dde7b0bf4ddc3beae"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bfeb0e0429ea5f96944651f7f77c41aff622e5ff"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "da9da0a39637516e93f4d8532fc375d2e535df2adcdb57d48a659532727a81ef"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52ce593c525095958bed7ecc4704341bf35f5de7"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f88fc1cfc11a332e8ced893705e2b9dede7bc8d5d5dc90d5e65881156fc88d0f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "645270ba84dffe36aa9b2ececb004ded72946e92"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "1013ba3d4690a2cc23dacd6e9bfdb787b71d1198c284af70f1cf3beeacc91691"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "e6e382c3592e429d19d8f2c62d85ead248b27bf2"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "73d76a7c769abc711ca50e69da5fa2789b914c0504ec4cf54a763301cd186990"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
