[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "728eb68d2a8a6dc2251050669fd499ffec69056566cbac8132d6d3ffe341a986"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-v1.0.11-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "3b5647edc1f8fe4329f1f5750e83c547376b2070"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ebbed224948f91faf30884944bb98e64884cbcf7f151a9d9101f82d43ab8f746"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-build_log-v1.0.11-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c17bd6b8ea8786abb8135ec6026ffd0d0e48654b"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d367c816f3fb8fe0575613933a503b159f640a4034ee602013a9c80e97baef38"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-extract_log-v1.0.11-x86_64-linux-gnu.tar.gz"
