[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "f97020c15d0558f13fd6fe79ab4cde25f566fca8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "df04d56d7518ad767efd2dadf8da75d099d4e5dacb0ee73d08da85980facd27d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cb4f9b8473c746a57bac068bf57f8127d4e48d16"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "8c90cfb3096ac029e8f0d432388b103ca186ebd73f5532ff290aa4c6b4827b28"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d69739894779e257c5660239722071575424f852"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "50ec49bc7515dd64b5dd9e6cb8d92c137df3dfba092a228154e2d0226cf7f6eb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8f154d1fae7f1f752bb553062f502e43a47c8b1"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "ca513fd63f00671e031d919a5bd69083f850a8ac4953548a1ef568a59ce96b6d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "f952e81f66c532473ec0628b69e52da64bdcc792"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "1665ac274d330ccc81d42f403981b2c9481132fc0c2e553f9a63b63b4978f575"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d91710df0ef9ccd3713a140cfdae051734982ac9"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "a51521bf8b815d87abeb46101ad00c0434473d7f9dfe09e5cf6a0f8b3ae860fe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "59aa733bf3bec8d8b1dd9344a3c878f879714c0a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ac9a07c59253be63661f476a7aa92fb5ffeed87bb19604a27bb5f812327f2ba8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "c69918757eb7b900ea488c0eeffcdd895caed9d2"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "69c09dfb832f2cb54c259fe2f98770fa20accd9a93c9f090fdd430a3c398017d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abb5c15c442f7c7d7d885ba49d4cbe555bbc1671"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ee3dc1d6532ecb91338cbe3690689ef720f18c180b3ee8588d8c0cf9ab81b5c3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "b7bb70cf8edd4d3f795131abeeed7f1f87308abe"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5b4026928d72e9eaab0fb5368067be0eef4f3cc1758647016e3eca2188a35c83"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4f4fedcba155cae1a8a417f810233ce529467ff7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "86b949342b8297f6bddcfaa5c89c23ccadbabbb110ea73ba3595903ed9b4fe80"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "a29fb3a1609a83248f2df81e90686962af12bbfe"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "237f4a85d648c7e0f2e7f08160f75378ae2de931b4bfc6808c9eaec4bd5af29d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "34253b22d3c27e8baceefc8fafaf45e6031fc3c3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "9ae6c224eb0e7e8fa1b64352437a89609a9f213d95a2aabf9cdbc8b7acf3a0c2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "687b72f3fa3021959f9cf1f43d4097747be9840d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "79b5037ddffe7ac45e0eae4fa4732646c86a96b30e8f8af4ab460bc33e7e050b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "b3206f192f49ec374231b393cb8835121989c0d2"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "db7d2bcb8351b890d92009ed02a178b03b33a5bc8f1d87c5258e783542293e1c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
