[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "38edf05eb59a60d82a62fc63caf041a506610762508eb97a14a623ea4398e1fd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c45665ad70f6391d612fb9da4e62d52398a381efef5776a5d09b4524d705da90"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b132c3f690aa8e51695ad343f49e9ecb1c5879616519d2e2b55d12b5f8326897"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "510e20bcce004af0b7a62ef400d660e272c51259d28530058d36292594cf4a31"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2ae5f13535fa375476ed6373ad09f8380c5d04f64becad5d2bc1edaa3f965284"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "8db619692e9b6782bffd7b04037eaed7a085ee12e12bb38f87f03a92a7da1fd2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "2c260b8ca72ab8bbdb661d34906f1ad8d276179630b17a14ac4f6e9b97d0f19d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "abed62def06d41ce241ecb6af45d345a0b8e87f067f9208a4d32ec9d6387b07f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "2041512b037b2d98b0f3a47e4df105a01dd1f6fcd20d244aab22429514b26a3a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0bdbff772dbd14a95054b918ed479eff4cd5b26d9a08ee5b676f61b69d0d91dc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d460f712ecc394e2c4c36de52312e615f6384de4b46fefa37ce0c5a473af07f0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "9b062b471ed05cc99997b4244599844b234ae0995201ae95765c1f57a1a1c6bd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "c7b3fac131bfe6881e11c668c7a824f2494f9117237082739a011b136d8e1179"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-v1.3.6-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d0bd8c947bfb9ccfe2595c2f0ad7b075aff9c209"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "2fdb99b3acc19c31f2a85e3e6183674aecb0f3f65bb5bd9b1ccc3710ec9a6ebc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "37875b4d70855af3cd5ea032aa0b5113f43624bf"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "68ae955d3e3d83ea9c6b5e61a52d194d01aa36ea79074a3e3527ac46d55d16bb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "74a6cd4354901b5a7add2fd2a97d92fd8cd071f2"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "4e5c7d06a3b1e8a85548221d945e64a5df1a7177943ad97d6213cdce143521be"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "daa24c280b13ffc4e12f47c5871a5581c3748b1b"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "4596a39bc5f9448a0706e19c7ea17ed4ce8772e05da478fe5399e72f632708fd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9751375a3db1374f589458937014e4ba5fa3fdfd"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "31cac92c6583dddb54ef32808cb2a89eeb56e48d7bae8282841df153d8a064f7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "5c2550f1b30fdffb2b5009372a9a9c3076c2ddae"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "854c26500ac091b56b8c9fde7f53b1cbf228c046495be5ac453dd7de4b4552eb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d847292721c22dbd2ba4e860c7427ce62e51a820"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "2c147fab6ba5d2a66ea508789a92a454eafb35339bfa7f9e9e1bc959dc7e7d6d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "751cd4e09cc6edc8409859c9be38542c5302af45"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "a9d7398aa6e2ce39b5b133b7e954ea5dfb2c595481c3fa0c2de38f74316c3dc9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "04df1143855c5319dd54ed565258da95d99591bd"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "dc091a0c453a1df875f4d10f2da50a51959375aad1c03626f33fed3f2d156824"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7ecb61cea4d9363c7320f49f3ec0ff5be242d23"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "60cf9760d7a4cd99fd1f214343be3c3132dc148a97ceef6d751ac8bb88c84465"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17c29d830363bdbb1d135f188f7846e58245ce63"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "a64ac3e2ff53b8f37e0bc2bdade6ebb9fa78001074f8f3d0dce3bc0d19ef6dab"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "f82d54c3dc9afb5f66ffc28a243dfe27196d44a4"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "6836adec36ead9fbccfff98ff420650c0374bb713ab9809db11e4c6b8aa07e61"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "c613b9a4b639aea54ca64ad8c57e52baa3ca19d3"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "6d23e262a80730a59e098ae6f6065805687993966711b7fddaa100948919660f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-build_log-v1.3.6-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "675f559032344522de2b7462f07470ede596144e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "657ea8c7df0922b61acd946420b069725a46466b2fcaf4faa2e695b9c5899711"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "ca7101be82dfa84414d0a6df68e48d83d74e71c4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d2f454ebdd68aef6811137036b53dd52035c308d81f5c24c05694e02eeee7d0d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "c15a52f0be2ee0600d67e64fc26582a7d4fb6780"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "984a275d44abb529a099d10077e8ff343c5de488e062e91e3daf31c53be51067"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59039f42d427667a814f5c5d1ee3c47209214df4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c22cfee1f6722780889b8a41df6e2d6b98c398fdaa461b35f44f35bf0c5171cf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35a259059e68e8b1b25323f37a571911f70d36f9"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "7f2ae370bb6db46aee729c2ac85757a738a22995aa427a8990fcb4d3f964cd48"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "47880973891ca1a2c4db6a21ed92de14d322b81a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "6308dfb61f03a39626392f9faf98e24475b993cf7e9bcc24ea95d764613e85cb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "314027793eecfd06498f3233801dc66a5953b8bc"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "0cbc5f7e9e7c9bb4405164aa23970ad08037d0516e750dbd8b73daa6848085e1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "66f55736f4f9b9fe7cf73d404a049edb37c940ec"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "0e5c4f45516a7ef0b09b364aaed36ac15fa776a38bbc0b7bcbfea5b06586a39d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5338d7bfb8c569f0049f305a6bb5f406c741940d"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "90405e7456e00987ca0ad2dc241bbe18e57fa1738b70e8b3e62896e136766293"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8149bcb5fcec521a9e85cbbbb0a0eb40e860728c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e1202f0e95f5defa120e6f0003da80c28834452fb7322bc127cf69a08da893a0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b31a037858dae76c993526cc027949b0bf58d35"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d9740012de38114efb96a273a4ccedc3d67f8331baa6b0bd4dbaa404801fca42"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2e3a233f069ef7b18578e1d34269ea0485d06b3f"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "9157de19abb9550b1e0fe24ee381a997ca50d865e3f3118f53833867c3c15bcd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "91c0c5b7c3b3e983c1efb472e3eca4a58dc11a1b"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "bd5ee055d844d45e4e05345e331f6fe5bb7a2923013123da1d9cebe36ee82c79"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.6-universe_test/Zlib-extract_log-v1.3.6-i686-w64-mingw32.tar.gz"
