[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "fc37efa53aca6193af176a90b09880165e4d61fe806ac10308115a747367ef21"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "6f956c6797f5cd6d096eb217d4a9574e5d0613f1e1c378c878286ccfe115294d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "6ec66e6d2014f14167faf082695f0be4dfd1914c59749dce4ee28836bfca63e9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "a6eefe1b54d318a207ff3a698f6aac3807ebd74f50f11a76d5325297f90d0b93"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d26000ecf155748430d1e9eb919409e5f5231d01d567c25322bf4e174d152366"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "05c5ee7c58ff1de4d4ffc190f1984b359fcb07a72c2185cde3d329e7beb10c35"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "016ce766a3b9ccb10739bcbd8a3ae1c04ff7b3e1fde0b304387cb0e26e987c0f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "b605d15c3dbbc8f72f72fe6cd03be56ec9fb9140aaa3286579805ed15c967db4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "299c366a8c879c499e47230c3ee64eb6ce2c792f7986e6e1b1890627c38ee9f3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "c23801a1ea75d932ef2699f602ef2ba379a1f99bdadaa17250a046fcee6e3d3f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "79db971e1d189ee23a9257bcbb36545ff3069fc82bd2deb679bc8d06eb8eaabe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "7bb5d8e2230c42bbcaac44b879ba7a815919ba28e86eaae335112a994d31f1cf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "666df0acd4d5dcdaf263d9e13fbc18c9ddd9ad2d390ac06682c0924c02130ca8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "7e56270816f488f85d1154456a8fb472dc02d206"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1c19fc58040401d7b6f7d244de4bc67323c5f5d37f7b89c96757cb1566461470"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "ab7bdb235db317f9ed8c95cd3941092d9f6d5826"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5b0ba80ad92205b29a602428d802394a5983ca5f8550c74efb25ce04916189cb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "f2cafe4a40395eefeab54e073a40979086bc3847"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "9f8aec1fd45c09a352ae68eac4785525a20131c82b5f98ca2409bf839d09ba25"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b3e0193f5dbe9d5c71de4c0d77fb54efef364be"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "c02fa412b8e2fec152c552690792120060b8c6945de0fd0b8e8f57d4fa81606c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40adb05baea8cf0b2e685b75e7b53a8acffae5d8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "2eadda7ec8680d4f67c300ef6a844472e70e4c0df38e7d13a79e21fb36a093db"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "bb800a71a179d270c930a43574b138e30eaf679a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "839964ed3c449d456a3cd8bcecc88009b83e6eaa79f789358e2c3e9c3bd802a0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "1353d0962c6389e9fbabcf03eda370dcf6490490"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "fec6afb6476e3a67f05885651440ab8610b216ed9db36d442f1b68f9ffb348d1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "d31710cbed47ecaccbb6ab508178eaf6f4ab6bde"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3f4c2f6ae93cba7c0805a1a0d1505087142aadeb25d836228025893b6fe6dd14"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "d9d717e9b7a4330aab4f76115be64ee5d4d5713e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "db851055fc3b6d24c008bd2b1892cb12836732894850d8ccb97548379b04d51a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1acd87c8f2c0eca4a328d098a1cfdb7832a1d1b2"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "a512d8cf8477a2468f18ff190211a1d65c7e49c53ce5e1b40b531e4f9ad41e8b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2d841534b2942e3dce7f50e93a905f9e917fb3f"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "c38ab13effe299b78ab208ae92dbe39f84c5ec70b1ee946f576fe4245f823fc4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "843722847c9d3dc9d72ad6cce9bfdcfaaefc76ef"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "3f246035ed7b5785a56750b7d7bb873f18f5c5b3464d47e0aeebbd9e40f50698"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "c70bea5eef13856c3a4e202359042638b1f33745"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "0ebb8933088bea556c746a1ada77fc1cbe8831d8222bbb0ebdaa7688972fe60e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "96075fb2d339030e7406c6dcf35a1fde84082ecf"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "dbdb9a5fa264590816cf3275d8fc1133587254405bf59309c0ca3a2e90d69d98"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "7b87ea0e580b93e11f7609c1cca6e6a9b21813bb"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "961e5883d7622f5d83deea2f31ae349dc0fe09fda622c1bca774ac9aa9f78f87"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "eb941e0f5e08944432ce113315ef97ed0f873108"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "4b3f58b78d29dd2b1baa15f1487f092e33e4178bb751742a648f6f1c0b2df0d6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b998065d226dbf078624a965b5dbd546c9b3278f"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "251702f81b7204d4b10312d17bc7ff859c17a1df8f4ac0bb10c49edef9c365f5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc42894c57670630f9fab17ba5bc5701bfc0402b"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "aeb77d951a94b683fdb69c17515d9d8292728cc6f4cac55d710ba0def7c89805"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "fa2f54fe6df46cf80ffb9f829d35a7bbed7e1c03"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ff4ce46e30c787cc6c90fb624cd1c9ae5671b22378fed1295a724d34a57206fc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "eb9d4aa712c3443c27322eace9bf90429b1371f6"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c8bec18069e130d1112676e6a027b210ef7b973d39285bebba78e7d6af86156f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "e837c45ffa192337240a3825fbddd55ad5c17aaa"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "678a54c82cd090f17b8d07ef00952cf7624e6fd4a2e3191f42142a2eaccb23d0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "53d537223e1876f5e8190609c17899d343372e05"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "df891e93720c3ca651c07c912dc63ee26caec935ebd82fe4cbf84450db62e7ad"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9fe01ab99975d2cd19d0afc253b949d38f758da"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "47215ff10c63cb7e87a77abe763579a52c45246b2037abdeb46ac5ce01004e54"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f189f71f71bf4c3218e33012991bd08d609bea2e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "5800510f6401353eb09ea804984483303c58455bc2f7560fb5498cde2708d988"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0131d1bbde726e61344dc2ec6a1edd815702eb82"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "8c29bcdd6a6ecf947df9b5960903162443cab803d8da0c87e8b08969aba8762a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "14e753ad602c6be670a0c31a58ddd867d513914d"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "f236c44284ad4ea12a1cb1a5c34bf6c2d0fb1ff4dd9c1d4c48904fe91709b7fb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-universe_test/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
