[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "17ddc4f7aed8c2724a0ef26b0dc1264e05815a52545c9ed558f7d47a7209a004"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Zlib-v1.0.1-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d2a6207ccfec56adbd652f04fccd685d61dfed26"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "6f4a096568568a8c645aa8fd1f423041c065bba2825402bc29efbf8000a3082e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Zlib-build_log-v1.0.1-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "19acff8be8abcaae4db160cad93166febb33385a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ef9f7e6992ab094091182cc6af2587b740f689dd5705d0a0c361f339d5a8697c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Zlib-extract_log-v1.0.1-x86_64-linux-gnu.tar.gz"
