[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d5f68260e5f72a9bdd4ddd52fe1b5a8e9893e119af297e8f69918c0d4727f3c8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "44e2085e536db889fb9f7960d872487e87518730"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ab326b8198cb1274fcfe82da6947e53f4ea454ae567a4659ceaa210e0d4b0bca"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6c9a2b492fbc04b44a7f51836cfd93c78ac14dce"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "5381431e634fc63f1d2bd95e3316e31292c01a2706941c69a75468ec7089898d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
