[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "867861eef4edfd96cd1877e3c6eb39259204342a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "3b7cfd98a1131549fe358cf4eebd98e2c5919b27d04dfbd8711a30d150b2fd9e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "c8c6516ee940d032abc74c5b85b6d8ce7787f9a8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "62bb5b21407f8a42da3518ae182d950301e17cbc8778cb11113f91ed2ba2e7ab"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1f32f1c1073aa844438af77f4d0c89e025b647f7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c8f3ad8090124a2d30473531b1d7a37f1e9db1defa807793282c6b84af7bdbfe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
