[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7a5d773e25828f6bc17916205a5f6967aa984784697bb1f7d51bf37bd5a60344"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.4-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "ee983b2ebbbcc78340823e88be5fe944a93acf23"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "13d0540e522a7a14a23535f1075ba62caecbf0e8cf3c40349bd1a8e99d409466"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.4-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c0fa520786dadbd1720f6f4d5c08f73ab6698f4f"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "905de8c8e0f9a368e16898bab27055caafe06a3637401c92f9b6f6ef2a440d8d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.4-x86_64-linux-gnu.tar.gz"
