[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b88263699591a858c1cbe623dcc22ebb10b747f52e1bcae4b7d12b8ab9398512"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8d7dd799e243615a4ff3fff665916dab25769b04"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "281a8c0e18149234927c2bc4198cdfbbf7c256009edddf74cae297f68e2968b1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "2a85c844c6d50a72bb9b4b6bdbfcc6150b2dba6c"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "29b7f8936f41cbd88589c92827369281a02ae051b53c30e36c74b2a0b756f759"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ffafa4329960a0af6c1a8588f55fe6bf7e276f2"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "be4507720ed37d706d8e9a80448e8752da52146d98b0835ba02e1ad8d77b4bf0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bc8729e5b8cd954136d85453adc3178f34b8a6a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "6c971340e5471377f4b1d59fbdf832419931f4c729a68b3ffbee2d7043980726"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "e499360d1bf2833af8f9b11bf0eae2c043a882fd"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "f74afd26bfe9b407d30a60368b9682b1ff0efcb8f1bf5b7a5dbf494accfaf519"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a956eb54760dc986c3aa489f57907437885f381b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "a86d738483be3b53d8fb5aaa4889f3be18022cf5c5929ac687bf4da792a5e0f6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cf60b4a2b7f2d94e91ace76033ff06f024775e0d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "8b86bea9da3ed91c04e509c108e980eb646984bfbc188cc19d873335377bc8c9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "bf18fe011fe76397bac9510361728a8c297e94f4"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "e6d1b70ea9394b6a1b2237b9e58d48906fb55d9d939396ad324643cd65f46d20"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "688ae9a351fa1e2bcb6a89e8354eb1561e7544a9"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "7a7fb494b073d8a1489516e3cbed708fadcd5a67bdefc0d4726251f67bb5fa25"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6252ed6cde900b96ad6494a9a059b5d1421b959"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "e0563ec9254d3fd22473685dfbd15cbec28ed6e988b8e294ab7a3ec580297319"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "1390a92df1aaebda287ed3c4b1a9f338ac935e36"
os = "windows"

    [[Zlib.download]]
    sha256 = "33db6cd96a1a8e8354219d60a1389b87f41837a21de75bfb4cb80687bf9adeca"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "e9e87557be7b90eb0764524ff5833e6de76caf0f"
os = "windows"

    [[Zlib.download]]
    sha256 = "2fe29c2cee899894c0c7f156a1628cb96e972a5f92a6940f7c91006a9ff7a61d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "c0e4c7e43fcdbd7ccc7b18d3fb269e42e2f8e544"
os = "macos"

    [[Zlib.download]]
    sha256 = "e3643027b20da5ed13f73835417d345b2538609a1ee72046804b5c58f8c27e87"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d5d0fb7814c9eca98f2a507751a9122ab972fff1"
os = "macos"

    [[Zlib.download]]
    sha256 = "a51788224b579284ef15cefc411a46c2a8f7c25f42313aca675411398fbfde27"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "956e8a8b6d42751fc0ad21cdafb43f1276a432f3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "8783c6e97c10e809e72bf61dca72eb9bcadbc648e507d196aa63af97ceb8361c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "38bbad51567f28476388e46a05fedc9b7ab54137"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ff5f6ff5f466a585c3efbb5975fdf4d09619013532cac060749881c531caa435"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "af2e7db457bc041aeaaa9475e41332af9a788f39"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "6e4c67c13ecb6e675bb7ee3bf55b84d6cc87b322cd1837cdd795d5b7aabf0437"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bfcb194a54ae42a0e915e47f45df238dcb8c6dff"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d5468e82432994f704f5efec77c1afdb2b66f2992e48a857e0b258a271adb1fe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "42f7d6caa9faebf466c66a44d5ece00258d623e3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "25de392aec7e7dfde1aad3f8755585d78380c55129b2e069c7be0aa9bb607e4f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "c04e9bcd94318b17da50870e215f6063f53aef84"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3ded75b080ac7b1a2b2095227972483e44325f022a03b660b16c77b7ab1f5c78"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "9fd6bfd2087a18e409ee53445c954377415178de"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5865e0e67edbc096e0a1085535a1d417ae980bb4041e007d0f261d984ff5c43e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "0d4bc6fccba9861c5948f03c1b9ade56bbc5973e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3820f96763a150d6520dc31bea4edfc5f3b0a09e7c848aed40f7b450a00297e9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "b64322402916dded55f70df91e637c3d4f082a41"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "1cf0f00d193115fea501c347d99bc20787f911b0b5b3a86c1f3e8136f085f393"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8aaba786b481c547ae9e9e2aa3c8c1f239728f17"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "41a6635a8639e32bc47cf4a9322fd2cdc7e7c6a61966ee5ae8ea40fb65e5eee9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d287fe6f1d9e6659befcca3432eccd7a200c2d4"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "58c69a893b869f98767cf536c7e9a4cb314d62082d589a4d2cf27883a9c63cc0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "445c0a99dbb83d28d1063f65071e18699cbec255"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "730e4ce136579d3c9dc7a737d62240dac03607bb1841974d4db397e75cb021cf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "818053f065b9834335d658c3a91b1dd96e6e09e6"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "116cc7cda71227d44cd844a3e6b896ea5321b3b529a11321e3db8becf1d57401"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "b35a518f231d626f528e47884d0a05d519309113"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "4b05a1efc5c55d5c7bccec5511f7e8c903ec51d9e2e79616c5a0b15eb6b26ded"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "ca7baebd37a07c02ca37284f472271f9cea85163"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "281e6148142b68763bd9613a18d70a277a50a34f722527971ff713fb2408cef8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5ddcc3421c8ac4657593d326e6c2e8d4d093644d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b46982250288b8a248b64306067b98cf59a990743fb6b0b88bb3da16ce2134a9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "f4078030c76a90c3f1a30d442beaab15a74e1658"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "377b233352c3ecc7c0206d3b3712c01407026426aa59891157be22a388a004b1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "6b168753e588adf6e44080b40ce68bacdf78abe4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e7613aa4ce9a76c5d51e0c3ff73358f047c01a7d3cfd97ab56899a9ff575ed31"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6005dad0411a694f84dc24fcd21133a9963c6c31"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "45fcc3550a10db14d0874e867dc875401d7788ddad7277ded94390a4edc9a2e6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e7fbbe0627c23bbe80eda22e551dfe219106aec"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "24b88bb3127103f3e7d66c65c8690b90b0047476214e6463cfcace760ab90cc5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "8e0611ad5d6a681104f42be8f028f6de8001e4c6"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d9787e63d913fcc3cdecc2590aad233ec3370f15cf94862135b573d9778a85e3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c7dbd5141606a6b40343ce3f1fbca503c0eb9080"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "666793c9fdda243c6230c85fcb3223bcc318c0f51c7a8955add337d57b060371"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "ad182f41a5257dc7f53861f5a49aa1f54a234f62"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "42a1425d040560c9c43d032d93ada7c45d7c50ad9a833a53cb5600a02bd697b5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e41ebb13dda30751715f73997ba427abf74b27e9"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "350c0842ed4f2286e5a9ebfa7b3bdf5d797dac058e43a25f6d75d2160e290361"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5cef7f340797f7879db89e863c26b954d84b18ac"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "589c04ea57d217133d44ccb5e57c3a19dd4894a88993b3feb61bf5a910013cea"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d5de430fb46d286f38b681801aee32dfbdcd325f"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "0f5a54b290b383d1169b1346f9525d5afae4b3d18ecb51c885a31a0023d11027"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ca547d06e149161ec87bf842a81707b38de708f9"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "ecbf22be3462129f6ba63502f5080a8d466501881a8d1539a3363325b9703e9a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "3a73acafb11cd99c38f1b3aca1dca1c1216c0457"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "337cc6441c28e7b79e89bafeb7ec1e500d20a2d943745c2cc72d42960012e01c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9662feb5fc63f8e8ed9ad8f69f15246b89201a2e"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "02a8f3f176bcdf449670bd2c2f1bf78be544e497a7d431e528e0cbbf05c40258"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "881cc4834758412618f0a9c698ee87814ebf933b"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "53a7ad780e2ee91f1c7ae541af4c3cbcc8f8f78b88a11405d2112fd473f2d2c9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-apple-darwin.tar.gz"
