[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c9a6088b4c56c107bf41da5b65761be0520fabd586aa1491119628e9e0281143"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8d7dd799e243615a4ff3fff665916dab25769b04"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "81be200850a44461c61d1a0717a5efebc6775f5bd9ee8a6bdbba8ff3c40d49a4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "2a85c844c6d50a72bb9b4b6bdbfcc6150b2dba6c"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "bb0d2d2d6ce9ae473b61031fbda0214809b096750fa59ae91078c038977695f5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ffafa4329960a0af6c1a8588f55fe6bf7e276f2"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c9e7b8d2ab8473ae4db903dd7257a789fc8e3232e318d1d728628019ad1a2484"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bc8729e5b8cd954136d85453adc3178f34b8a6a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5aca546f7d4500fef8e9c82768a8cbef196d32548a3dd80a5787183c34f26a98"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "e499360d1bf2833af8f9b11bf0eae2c043a882fd"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "534adb54220a8d9c1fa7efe0acb9f8c166c066af1c0639e093ea9f62e6efdec9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a956eb54760dc986c3aa489f57907437885f381b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d79f34cff6dcade6c79763c4530606326d0fc9ac5f8ac229e69ee87f5e42d92c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cf60b4a2b7f2d94e91ace76033ff06f024775e0d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "be955192b63f3fc44899e52489985892f00371e3705466a4f450ab775a11b714"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "bf18fe011fe76397bac9510361728a8c297e94f4"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d0754d5944d687bdeed2650b32c8f9ce0d17c686f976e1f7519b70271b3bfedd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "688ae9a351fa1e2bcb6a89e8354eb1561e7544a9"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9677c2f8c4e37d4823495685008ce2e5b9fb3b2a1aed2ab4f85cd4fdbb550d94"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6252ed6cde900b96ad6494a9a059b5d1421b959"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "3c864d73af4d71a66013525091c21ad60aa9d1325270bf542f6443a322e1365d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "bb6b2065d64f9997f35d5b49102e190de7ee059b"
os = "windows"

    [[Zlib.download]]
    sha256 = "4969c95c90509d2ed703d1a6f50b32435375e07854970ba3dc06cb18d3010357"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cf59508454bd537a1584a1b4a099ee06f8ffbeab"
os = "windows"

    [[Zlib.download]]
    sha256 = "5a192ad40634299ba76da244de59674863f99ed579f1fec6086810ba6113f67d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "c0e4c7e43fcdbd7ccc7b18d3fb269e42e2f8e544"
os = "macos"

    [[Zlib.download]]
    sha256 = "80c6abb0f67326e46f97e42d8c360dfdc15cc977e88aa6683c73e592a7c61f87"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d5d0fb7814c9eca98f2a507751a9122ab972fff1"
os = "macos"

    [[Zlib.download]]
    sha256 = "ab12b8df3f83ad7ab5acb6373678ba75946891183da8563e337a7d0b385318f5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "aeefe3fb0e4d13199d70e717eab9f876e8e539c0"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "589de320b2f79feeec83a298720939d45c0b5174728ef77805cc371f15bb0373"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "963e802b69acc4ce281a899fce0e2aeb7d85fc13"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "37d4f288d2fa1bc9ed1dce8a715cd963af71b2c82166e3e8065c29b411916db0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "be6efb23dfe11d5fc5a023d93676e72da7df42c3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f702583cb0494090bfa0d139d7b8f0539d0cc32fe0cca46389e9bc8aac2babef"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73b3856b0bd21a76db8b10f9309fe8a16b1585d4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3ea3b906df30ec2a65a1fd26a6b467f4ec6617d63ab567fd59b973c38f257994"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb81ba06ab513d79286a7804c5a41d093ed90c1e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f684ce7dd6e32d90c5e45f6733048e8119b0bda60c3097930e0c7a2027e87791"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "fff1b2e55c59c78c4615a488694c7d1b55f0c3b4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "817d41069c790fbd43ca9f57ac0c24efc2cf457c5f9f3efc84fac6f07c3e82a0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "0fed7ab65825e0d42d73692c6f33087f29cfc34a"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "b5690ea674e60039b9415ae4d87e0f332996040d660233511f25adac1c325bb9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "7f7fb299fab83d6bb403dd1108a1654130781159"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "38c9499c180429f9c337c363cd4c8bf62d2322f9ba50b582d59866be046e82fe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "ea7138914344402f4504973f61c84dd4a0eece24"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "75e7372ab47fdfcc6874fa11d97ccc2f4dc0fe90e08d5124479b924261835c32"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c13f2ab469d0d516f97ba136ccd2478bb2d4cb90"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "8cb3d7f42e5f632864aba7c4fd07b6e78c8cfdd8f7d60b1621739439d90a66ba"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "142263ef0605f6086da2033fe9bce0b0e7027f52"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "38c39557d5a135ab6f389cde821cd198c8cd1fbb9e927e576704d067a291ca66"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "697fc6ee2e0ec31364874ac7dec44c3dea8e102b"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "1e9a9c92e25dbb4002ec8f23a0b5e2035b1567b9a6e01288c2b1717bf067f6d8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "0058e44344de3637faaf0f1c43da1c259ed6c27d"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "3b7a99f47b2a39e8a0c3fb5b0045b807e5834e5d071d71b0d7b23875cac7f840"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "2ff2fc4539cf08de4b6dc0d3b6a5177b7ea17ad4"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "2e0b09ab08eece14a548dc2d13f889d1c35048a2eb8d02042cb938626bff2955"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "5593f553d72817f6c8548f042e6846d60462d771"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "3823a28881f180ec5326ed6239cbcd3825b3e80b1262f01eef1d0df43bd3c933"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0f941c6146666bb9177bd3a3e36d41ecd4f95a2f"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b017f6df92978fc5af9350167c567111fa17430199344aa65902303cd67a29af"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "fc3b85a26aaf66bb2ba9134bd8149818bef519dd"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "711d427bb116ecfe5588d47e2b2e982c6f1d1c34f46ed736c8237d3a430cbd34"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "9b4b612f9acc0af312697214790d4a882986f728"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "9e3c40eea11a92b3111936542c96d3c88ac485a2eb3cd65cdd19ed7afd8cf626"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f801db00d6610bce1025fc9e89de92529211dbe8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "4313eaa1e56f40ecc586f3d039c764ff3c4afd2aa2787163846105cbf06588ce"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "33b0fc9daf8453945c962f2c5105eb3ee7b0091d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "46ec13564cdcee05d0718619e230a4cb77f057f138a610b79520a25e50982a93"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "6de863a1a08fba60a21c32df8d61e12a08b3d473"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c5d57a586bd932194c56866f1072bb8607e4efdd33b9925a8a837bbc3e3f5bb9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b2bcc1e4e44f051e15debb050c62ea9f71bb1406"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "a3dfe68a20886cc6629298f2b60ef9f8d951f3ca78f452e2e66c834600932ed8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "9f3a2dbce008aa0d4ec5acce09b699e8a1639c7f"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "bbb24073c277b52cbb08a6ea9b50361b4f03e5b3145fdd8a74cbde5c1736dacc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b32fd1840f6ca1596862fefac0c89d735f30096c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "fdb0222330eae09d0ebc2fb4dc7e19f5457395399f1c2aa9ea41ed97c9b88a2c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "423e96d5798f32eb7d1170b49aa025fbcc9dc0ba"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "5bafaf2b92ca26bc6e4b4e838606277ab03b8b3748dea417bedc92d278dbf6c0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f60a072084b471f4f78364ff0420e7244ab1e3d"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c42f7c570309e5c2ba94d620b9c8a0abce5f17c46489ba36d41aade5b01b51a2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d7982a2f72cb39f21480a5154ee2bac306043f01"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "ed52b8d489db3991a8501e6f51b7d4f7ec64405e4a2104eb58f891b0904eec64"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "2423ce7ea906ab165f2ab769edd8a0224cb241f9"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "7a641be72aec1a7fadc53f261b29b009b77eb7eac49e1f2dea04dc739c4c272e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "708926637360c993afe2c99b688b65aedc67b4f3"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "9340e20f6e576fbf4e91171df5a8db25be451c481558b1436f736d6f6779504d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "11e76045c2d348d6d6e490ef3052267d71affd5a"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "16a6e575f6c2f42deb37e3d035c030d0e13c5ee2e13de2bae2144613618ffca8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-apple-darwin.tar.gz"
