[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c6080f9ce6c3aab44ccf9be2923fd2b67707fff900bb24d8e2ab3f6826cbb8d5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "83708a8757a38ce65d13ba0a4755af3591ac6ec8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3dd286719edb3ae02267b45567c87f3b9e8e42e40eafc15629b9665a86fecdaf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1345082afd9bb37dc3a084f5c9939b5d6c23e51a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ecc75a0d3bfaf307c23e8ca923a194fcaeecaaa960a7b5d155af23f963b01b26"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
