[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "eaa4b1bc40755ff0e75c4b1e3491d8b3529211b68a4d8e2e85ca5ad4f4ced124"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-v1.0.12-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "989305b6e4c908d3b8a021de8d0f19dd7e214893"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "813de910d25769a6274ef43e1c3fd735315944777b16087c5c3156b7d841fce6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-build_log-v1.0.12-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "10e758ff4f593b650cee3aa1105ee2730044244a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "125ce01d928ab68d2750e84f6fd42d884872259fa73920e50b68bc322162fdd1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-extract_log-v1.0.12-x86_64-linux-gnu.tar.gz"
