[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "3607f2b4b752875d96fbc6a6f9bfb69a469ee4a885c2392558af45c40e964c7a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-v1.0.9-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "9b014e7f6981e6c9ee55ad5969e94a1781621424"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "629c51040efa13663cd47267bf61d60af27826d026b12d48d6137a106870e1d3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-build_log-v1.0.9-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fcba9ac849c40b74d1cdacda4b0201c4bb97e23b"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "2bbee9533414c8eb44ce2f3687fa7c220a3146d9635d8f543e4ddce7c16edf41"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-extract_log-v1.0.9-x86_64-linux-gnu.tar.gz"
