[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5483b730f46e61ac3bac969bbda9944738cbe5eae85558b643901ec9ee7c7fca"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-v1.0.17-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "b3392fe005d65f97cf3fe81df0a85f1a76959ae6"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "6f5dc32f66dd7e71620acca0d1b1ee5e5771b40314a37a5db3fe17bd76e8f046"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-build_log-v1.0.17-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "569b598bc86113c278dbd4584ac9635fa9edcf55"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "216c6d40d93b982c6b3b637a2a88727f050ee3df72543fc72f9bbf5573944078"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-extract_log-v1.0.17-x86_64-linux-gnu.tar.gz"
