[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "fad79df1a3794720bd3fd03f99904fc22ff0fbbe6d6187fee2e1a69555f1522c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "ff1385cbd748d0a032fd60fc2a0237d690ff91751bb7e5dc9ab4808953b46910"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "49343e68f8a1bd8f3c19b5e767f5ba8a69bd15507a9b6ad100f98207eb4e362b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "672f3df4723f1ef843e42c109ef390efb6b527d6ab012a36234c0a59847232f6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d0624e2b6901174c9b6d79ffc8f123c258686f4a6d886aa2e5dac5b8f819c5ef"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2cc839af86b10d407e62a983fee67f27cebb3bab34e22f2020c3e4c9bcc70f2d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "11b1104873b5ac9c6be7813f35d4fd6f822d20f616c099dfd9a1d01456bf1d1d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0b0185b52ca5b42c06bafe72bf9f52bd78fbfafe7d91dc2750051fe42b8f0287"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "b038924296146fa88fd92788f86e0638478919c15afe7259291e075c28c413b5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "f8f47bb1873712a0eb0dd7c489bef23e4c8bbea092fb0c0bdf36b6d74a4e2527"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "af99b45ad7768667b1463db408a626933b2f83898709ea6226884cbb70869fcb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "dc5edebc001034f2a54d96382e77f4b02c4975bb65fbe66dd83f1d0e4e82540a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "aa0d6f97688369dce8a111c781572e2bed60284be3aac13dc8a7d29e8d9fa420"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-v1.3.4-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "27a75a4083e812b60c5776398ec0c986af598c9d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "869b98c8320364f5922628026a5f715d3c99c32ce1e5ea6fea19222e7bb70c4b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "50757943b57d6e37a16adc43e5ec5abd97ddb066"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "03e67351a9a1391179c1a15cc5ece14251baa22cc1cfa8ae4432cb80007730e3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "07188adcc4765cf891650f3c3648972de1b8da22"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d6b1e61812be967555efa7a881e380625767bb04f3224b27b8b9b681cc733bd1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac0b4fde779e1dd84d7f590f89f2847366c0c470"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "862aaaa5130eed19ed263653c656fbb8f70121d83fbe0eae2a67716a247375f4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce1ec16f0976b5be22727b8be70b1abece3445ce"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "099160d27aa2ef4eea4448e55346e0c20b56648cd3c809d7b03ba5fc1380104f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "9fb0efa7535e586a72c6077e7fa060ad5794f54a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "803ecdc050cd69f04fc94c21a23312f665767d103a737d9adc43cb4af3babdbf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "6263919deebfd7b4fb28f3b594a46310af8ec238"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3949e8b63da02633f48433d36b4616fd0ca9c2c6c633ae9084007e7f92194dea"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "6dbe3fb87e22d692fa90fd224bcf55fd34430238"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "05722f3d4fe0f7137bab8a9f6010d9c66086c39a0c706ee9701201513eb106e2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "89afc28151940b5c883c8954693b23991dae6c7a"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "c7d22bfc71b151611fc36c7151b14a07b020049cd5e540c9ba08461252dd8661"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d6302c4448ff7aa47bdb1f9326a9251a9d71b04"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "bc488e763dd683abdb0782cde4a60242baa9b5c85f9a843f088c87286a8e1cfe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04e3db497ca73ebe3fc668810b74aeecfcab4621"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "3bff39e3e48c19ebd991b30087caca052768eb9d345a23b3ac4ab1ba92bbef6d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "e9526f683822c7270ec50412a663f388b34f6fe0"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "0a7fcc06d3829a4ab1310372ef71be1860bef4e33a3228bbaf01dae22d7c4d47"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "e2d1de85eb8e9e2a0c08af58a81dc66415330a62"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "15eecc27f9501f16b09089139deb763b7dc417ce1079f1c2fd34d110f1782bf8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-build_log-v1.3.4-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ae6a743e9782d893894f44f7d5d0d0e330102b25"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "c6f25c5d55798680f50ddd757ca441d3009d78061920160858d5a96f4db0716d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "a1c8593015d001b2449d9b2e3cc772e8fd097dd9"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ae8446cf7ad5f73279d66f1166c64e9f646fd382e6fc6384506c3e44cd47e765"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "18334697eb843735f370e8dc583ba438c7cd7984"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "4ef75154e34e99b1344c336790c4aa5c391bf3081075ff1239371d0e83e445e0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36c3cb5840e55707d0d7232da1e770cd40a4aa48"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "8905785844671a73e9958588cfec43f4f0100431f105d64430ff74558eee2b26"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fef07c2459a784d80cec5f06b6177d085a0879ea"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "af4951c697436f4e3ce067b46279b45eefd20f01ffefacf901b7273fb5e87114"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "1e414af0e5e721e44c96971ac20dc0860bad96f7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f5834f069d534fc90aa61165de904c22dbdee02c9f72533662afa86dc8b0bab2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1d878a8db47f8225cb9e83f5c334084758d0e212"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d431aef15e19d3c0f47e887f0acbdd3a5e58845f4219cdc6012399e0b2820033"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "de05e1bbff61b1cda34cf415a5e3bff3b026be50"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "e486fb8c2e10824df5c08abfddcf00357a8a3f4bab0ee2d67a49b52c42926231"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f590bcd70d98d139af8fac53c493b0edfd44e340"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "fbe6e4dd15c222125644b54c755701fbe7dc9fbe559c279fe9a80f49e32f3efe"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56cd042bb14dc51a30ffa08e34479fca82e36e24"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "52d330a4d5522fd6e1abcba1b9c97462122c6b15f514a36b21e2df3eb73726f9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f67a5c4f232a9791199c2c0543f60b32f2c309d2"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "d1ef319e19d02720662173c77d926aef196a800144cb57d9ac2c3c63d75450fc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "36174e3e566df0d05a73f7ae40bdb329d0564c84"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "ef201feff7fd4212185fc0df866ae9fd488e57ba78f80ede8150f5027860ad76"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "7927ee701a71f6e3c54a02aab29d9b7999a030f7"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "810c50a149f232c1884c2682c5edd671edbaa4c3418fdfcf5b0177ffdfc79938"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-universe_test/Zlib-extract_log-v1.3.4-i686-w64-mingw32.tar.gz"
