[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "867861eef4edfd96cd1877e3c6eb39259204342a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "ca3adeaf95fd9faa08446be15a91197cb5c4e2ce3520675903115292faf133bc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "5e2c3571a242f6a22c2f95d8811c9a33363e0b38"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "e0ce877ccf040dcf85ef091fb85eb82b102854b8ef9ff77fccdb60ffbba2ffc7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "66134a19943410dcccbb2e77e54d36fa40c24958"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "eb34d1a1e8105ccf11ee13905f0b10695d9062a04385daf49fea2a766f59818a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
