[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "184cb54b1aae058ae800fb495f4f4c7adea45e0d87bbc37b95c7422d4f656f2f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8d7dd799e243615a4ff3fff665916dab25769b04"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "41d1e34facbc0d2f299e4367e78a71ddc7bf63bb93a352ad8cdab3188b84c837"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "2a85c844c6d50a72bb9b4b6bdbfcc6150b2dba6c"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b64c36f08947b6c72ecf0f70326e2d2e734deb0b33ef04d3755ef43044ccc854"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ffafa4329960a0af6c1a8588f55fe6bf7e276f2"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "ae3ee8547b2a33b66139cb3ebb2c62c5a1beb4601789191b9eebc2456593c563"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bc8729e5b8cd954136d85453adc3178f34b8a6a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c2053d43cb88bcbda2c205541e12071f8f34616a520cd1584d0a753975724aaf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "e499360d1bf2833af8f9b11bf0eae2c043a882fd"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "75b4a2946d686d02a07b932d8b3f9a3b2f4085d7de4011d9ba9ee5168bab40d5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a956eb54760dc986c3aa489f57907437885f381b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "664a014c16d1ad79c65171f49c4084160004b7cb0588e9f0ea7433dc920ed355"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cf60b4a2b7f2d94e91ace76033ff06f024775e0d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "f923b3f50250a03e166ccad4dff1489f4056713f7687105352b7af11068d02f2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "bf18fe011fe76397bac9510361728a8c297e94f4"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "098404c965637f99de8977fd99b3d8de0bd74c66459e88544206d7de5724000d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "688ae9a351fa1e2bcb6a89e8354eb1561e7544a9"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "906178926427250ac72b65acd6db95dedba81c704778c25fcf9201de4032b2ab"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6252ed6cde900b96ad6494a9a059b5d1421b959"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "05020116125c44b7f2d10fac110e59503ad0c7aa635ce61c2eb46872000edc46"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "1390a92df1aaebda287ed3c4b1a9f338ac935e36"
os = "windows"

    [[Zlib.download]]
    sha256 = "3e5e3276cab1e700170c9cc08ca0c656551ebddd8c0e76686089f4a539ad6536"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "4e5cb1768fff1e5c7c863cc424e0766f38bef780"
os = "windows"

    [[Zlib.download]]
    sha256 = "e99a8c5fe020cc21fd3a870dd19796aeadbdee8c0118b097c30c653b8a5b951b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "c0e4c7e43fcdbd7ccc7b18d3fb269e42e2f8e544"
os = "macos"

    [[Zlib.download]]
    sha256 = "ea26e50a6d5c063ab6e98aa8d1b5fa7835bf3fe24ef15adac76ac971c0c31571"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d5d0fb7814c9eca98f2a507751a9122ab972fff1"
os = "macos"

    [[Zlib.download]]
    sha256 = "40a98412f483b6d9d024f6281da4aac3ab9f700b36c7615c50d2793a9f9f80e9"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "b6368f0f976324e4de5d00b584d01f6a03f2f08a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "dd4f18391850469ce90ae37265642f84cfffaa9a73c342440b1bf378616e46bd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "38bbad51567f28476388e46a05fedc9b7ab54137"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d5f8187b8a9eb2fd139403fcd5954d59cab82c71e717b90f8fe433d78cde1103"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "af2e7db457bc041aeaaa9475e41332af9a788f39"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "a8f16cbf4ea1f5e80f9813ab31505e672cdad1b5998510fb0a7037241ee498dc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e324998004b9af1c8923e978e46dcbfe17731af"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f01b9bf5843a620ba87c08266bc52345a044748cd0233de37ed4d705b960b0d8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "42f7d6caa9faebf466c66a44d5ece00258d623e3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "54d9cf810185716e73ed81dd0e0e00984df69c8907f21e076654617764e17d02"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "6bd080a01b94cfaecb60b9fcd877e008f7615af8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "2873964d833fe1cc973c405b7731bd69298a304c7e01097f17afab7c1f35aa14"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "e4b4f61076c5c8a34376f49812595774d10cc837"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "6bd5e3c077e25cb0328fec3120e3e42adfac9c4f9a86e726dbefba3b71a42704"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "0d4bc6fccba9861c5948f03c1b9ade56bbc5973e"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "f56884dfca51846d11e8cf6116f1d0a5abe3ad01bdc3d2b181b4abd5f9566bef"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "b64322402916dded55f70df91e637c3d4f082a41"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ef2c9bf9d9c8fd6e858f3b09c468f77f052429ac1c21e10c16fad8ae6885bca8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8aaba786b481c547ae9e9e2aa3c8c1f239728f17"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d7837060f3724718f1d15d366aecb7bc69cdfa7361566affaefe19a557f192f3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf7afa1db703d770f8adeb5d4322677d37a6c779"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "29dc9f3f9d3dfba01f02380f4a3a23bae79381237a2441b146f341f04f823e48"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "445c0a99dbb83d28d1063f65071e18699cbec255"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "87662ea72ac92b09f7add24f05f977167f797b02717f6c360dbd6af64d7dbc4a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "3a55c89f2c0b3b7863b78e1880a6aa62fe8c0966"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "46f6ac2f81bdbf66e6599e8c6b5e93adc4e1631a23760e3217584aaa2977099a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "4daa46757ccb42d7faf11f2f185e0cfce32d4000"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "4fba5829ffc87a656220bb2adb28b9fb88474ff61c51db64066e53767c70569a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "068b0f06ba957771e46da3bc03b50cb5cfca9efe"
lazy = true
os = "macos"

    [[Zlib-build_log.download]]
    sha256 = "95790eeabdd8e6aa3758ee6969de2f8dc3fbd247d7af9aacf66b5b2e9518c239"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-aarch64-apple-darwin.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f1704aa80c04a8f7f77ce76fe7729e56e97840e8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "0d873da5f0d72fe52d70ab4c8f70d7e95b88786a91032fa4d295837625b6a9c6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "f4078030c76a90c3f1a30d442beaab15a74e1658"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ebdb3ac78f510e8d0d7bb4ebf3e48c5a63d7279c1b6acd0d6b94f3a5c20ae858"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "6b168753e588adf6e44080b40ce68bacdf78abe4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "8548520f2be347568c1c40aabd20f2c44febc3a1ea7cf759c88aa7da5847f33c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4a6f16f46b62d758acd4330d8298c5a3d6ff6690"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "22a2e6d13bb34c21c2adc92ee93fcce7697ed919f8246fdd9fb86cca4264fb6f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e7fbbe0627c23bbe80eda22e551dfe219106aec"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "507fb9fa0904495ce6db609297fabf8ac2fab67017d32a27187af2ab30fb73e1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "6b1f5b911e76f8405b8422b57b6ca57ca98fc028"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "dc0c1d257ddbd3af8abb1d309611cf6716b6bd78328a3c1fcb5e817b82fa5722"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9659e36ad0243b5f0a8c9535f0ab5c2267c3677a"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "36fa097073f4290ff6a49171730a743e30fa3a1d4370a475cbad9a66c4b98890"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "ad182f41a5257dc7f53861f5a49aa1f54a234f62"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b6fc1ccb9e86410625314821c7c197648e15e9f6f7f2ff56398dfece719c1688"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e41ebb13dda30751715f73997ba427abf74b27e9"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "3801f8e635c8912df53e2cdbc0f42f1d7280f9ad3e46f5677908fe12c8f77c71"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5cef7f340797f7879db89e863c26b954d84b18ac"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "273ae4c1ce7b86e36a46779e8d6be9d39a577ba25cd8efe578a95a1d86fd34ea"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "268cf755b4eb372a611675ecc8412229df4dab29"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "1b50494548602a34d250158d63582158899805b66aa39c7bcee7fe371b021c71"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ca547d06e149161ec87bf842a81707b38de708f9"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "97099187d502ed280f69893d3fd1783da8ee740d25fee8af0a4ce68d27ac6132"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "5a05383b897b01d39ef5372d3f9b801c09c2f929"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "cb423d46ddbf870e04f4c479515c1b0377ea84fbfc264bafe2e0acb9427abf5b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-i686-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ceaac095fe5d763150982a9ea762c4c8ef9da0e7"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "b4385e67fd0ac4b9998f34ee6fc3c4908817a95d5ddba803f0154396606e780f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-apple-darwin.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "488166d2b33ec7b6b9b6629fe30b576cf2b5a291"
lazy = true
os = "macos"

    [[Zlib-extract_log.download]]
    sha256 = "0d3067fe2270ab9209010badeeb536c8cc0baa8db1a0679e77e9afbc38d20cf0"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-aarch64-apple-darwin.tar.gz"
