[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "867861eef4edfd96cd1877e3c6eb39259204342a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4c096ed6fe9e8e92c191f205823c0ade10fee707b436590648d11499315d6f51"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.4-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "4919d71b9966be1b4bf3a0cc3925905b79b1ff98"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "0eac0fe0328ee251a403ed5aba713930b00aae0f3bf18708fab367517004e494"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.4-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7cf1b85fbf49648a1c1a423cba49e205e29437cf"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "6fd1524322c850fcdf3f492ea32bea8f362b534cf9ca3d5eb2345e30c02041ff"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.4-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.4-x86_64-linux-gnu.tar.gz"
