[[default]]
arch = "aarch64"
git-tree-sha1 = "d8e3f1e039b7829a8e21922cc4e2ee5e4d5d59f5"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "c5a00a347ad7dc3c4f4d9734896212e8ad77309d256924576d76ccdf410f5797"
    url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "62bb012162f7f8dc399f865fc0ec57c8a6a5f79a"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "c541a0b9130b2e16c334e623715abf129a89ba1cbee7cdd1d655b26b868ee960"
    url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "73ab90d01bf7b5b7983a851d0bd31be6394da5dd"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "c9e2c127e7bdf661b90b6096f371bb80c660d4bd1f71896e0a09ffa35febc778"
    url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
