[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3a429dd0fa904f02798477bba387158ad7ca4fb4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4c313ffdb22b17871df40583d00d2d1f1e7d1fdddab0dde231a6116400b6df07"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "1c9d6d3cbae58d646f4ea8b4c6a3ddd53233ed35"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "8c86270d1a9ab059d24d6a2c5d4ec205b939080ab846e58094cb50ba027a7e8f"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a4a0558b5ff607000233e37a2810bc87b7fb0471"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "75592584922226888608f338074d3ec6128ae85fdd89d25169baae417a7dd7d7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"
