[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d3c1da6d3609f9307cc8115126be8c41f5bdb0d71b79ec9de9aebc338b673f26"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.13-GCCBoostrap/Zlib-v1.0.13-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "20c8ac7f6c030a3289b7c6749d1b73a0cea5b452"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "cf05725b010cbf4f2a5d71f5afff0159b6e5e4aa8c43a3f3dfbd539673d0afe2"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.13-GCCBoostrap/Zlib-build_log-v1.0.13-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "061432138804d683b94989a3d9ce7b79f048c1b4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "719fbeecea4eceb40998604e80d265d69d21711580d366a239f1850d40ee0f95"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.13-GCCBoostrap/Zlib-extract_log-v1.0.13-x86_64-linux-gnu.tar.gz"
