[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "9b640c799c6f2f66bfb4a532cd5e20b0cc57e803808faee09d485464a45abd26"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-v1.0.15-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "7ebdb105947464dddd739b1f9d257580fe66f94e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "de180b0627d6c427045ce2887777bca2a7a796f41ead51813492c7591ac98ac4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-build_log-v1.0.15-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f40b593cca31ef89c5a88284ba16437225a00934"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "748be8e2b65893a7530f85a8aae13dcec9b9aa60d65713c02c3cf1ad8fe933c5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-extract_log-v1.0.15-x86_64-linux-gnu.tar.gz"
