[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "881524c8f7463c67455e3b21814d751b8dda7697"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "28535e1524c1d62641cbc115215eaeb8c305c664cc567b98e9cbe0f2d45eb3df"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "abd852db730475f0c512cea30ec89c0e3396feb7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "761ad243ea235f15b234bb5c1deccbd35bce2be4065b5ba1389368c98cb9598e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d443c5d4ef912c3ffaafbeb3b391380de1075d32"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "dfc4095c4b321fc1e905d9320ebd557b52f097111850930ffb4d44632581841b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5196a2d7c2e0d73068c08d1964053f5a5ba634e5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d77398a684427bcc1f4ed86e8686c3ef8168adf20367dc096217453f0e38846b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cc1d7d3af102fbb9e07f1353d5009e0e0d30f45"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2b1b2b4fd7f89f98e32591bc1dd021dd98e96537c5e798549b0a459302dfc33e"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "83bf31fa70ded0df7ae275c8dc2d69eee8d033f9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "bf8f90dbb9c552d3b8e633c3a0dea149b8ffc38c4833e6c0ca9111a145addcef"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "39ed9d1f2db542d64822d6da01a484c6bcb9f53b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "b7d63729d472d30ce2139f0d98d63a6c48185e8753f99b7e6e5d1b088d78d548"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "77fee933e35ccbc57f1db06d9a106659450332d6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "3775f2de5b8e9ba83e0b5d3582cd394170d5bccab5f0ab799b5f48a3fa9dbc8d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "30d112ef518a7bf5e26d83c6d295bd5c7cb07c3e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ce9c88b3753e82261ad424e7535bd79fd711748fad4b9e7125784496ed3e2970"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "279f462d8c8942514070b198fca4a6e0326de572"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6621c1a15ed2045b4b9bc379b209f529edf6d7aacac1141f8246818622dfdd80"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdf24fbd48e4e106821ab14981e7720920b3c342"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9f5bfbe17447cd532180f92549fea0f985ee12382b9e45fa3d78c9bd591f41b1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee413aee5a5d721cab8ba662e215fcc18ec0d126"
os = "windows"

    [[Zlib.download]]
    sha256 = "c758d1b4d4bd3d57455405996ba970a7427715673a46d08cafb9ca9de9f7938b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "896b920d4fb3fb212fefa38de3c33aeb54b2b0e7"
os = "windows"

    [[Zlib.download]]
    sha256 = "2c9ddba2f4d7ef2c38c291b5f4bbc9a0e4a17228638ae059cbdd5585241c1ef7"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-v1.3.7-i686-w64-mingw32.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "1b68e23e597f13581709cd2af9b1e09de3ef5ef3"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "dbd308f604d97bc6d972557c64f57bacd2ebadf528e530c6038d3409219681d3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-x86_64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "8d0e54ed1e3b6e7b6c06192e5db7914f130f3173"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "fabfb0710ae3b82c9197280ce6f76c5229d1a50595147608466788954933c03d"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-i686-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "14c7b63268f3ae7f9c100a1cb7cd7d588d06ac10"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "203e37d4c070ff9700dbd78e90a9de6098f19c0302ce06ee33b5cd75ec29e3e3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-aarch64-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50f38f87006cf42e29acb1fa743e3adb15c1797a"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ab78da96b9702afa456f9a57185e30068e11f86afcecf96f419af62a86c9802b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c3fb2debde1011340d2f5e356ec7df6822c729e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "d37961d50ce88d3c850a67c92e6cb8b975d05776a2b527bc31e2b0c9c8c423dd"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "a08a6728c6f4ebbbc6356b83650a03521c32c9a8"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "e7cbb0df31087368b354c90848327ef2fc8b654f5d776372424809f756ebe1f4"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-powerpc64le-linux-gnu.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "7d7c7988c03e7796f1b385a08c225cc46a5a545d"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ef9a3c5131db53b427b439920fbb3ec4f48bd3c292cb336a3c2bf4848788400b"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-x86_64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "b82dc6c4fefb04cab853fee11b6ce72be6e39ebd"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "566b0bca5c3161d3d8cb75fac5980053565ec46219da52d28e244581730865b6"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-i686-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "aarch64"
git-tree-sha1 = "4e8594597031f51cedca5d7fc264b6a08ec44a79"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "2a74863dc49cea9aeadb34cd5e4d49ad535695740a098d8bb507d7a07ee9c4d8"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-aarch64-linux-musl.tar.gz"
[[Zlib-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ebfaac346b3968998007b7ce73d5e232299221c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "17f5eb4996ff73b9c070f28d882e31f0524ff5c51f7505a6d579e14fb47e7df1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-armv6l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af93c15223c186a3bd3c426be3e8df4888181f4c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "ac9951f2115eb9efbca1622df8f88762e1c77ff8c010f5309fb59394421cd736"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-armv7l-linux-musleabihf.tar.gz"
[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d6f59c614246f1abc9b13a777fc4f712f2ca7588"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "fe9da3d0bfc6232428cf10ca38349de453d64651af80eebceab16f35f04e9d2c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-x86_64-w64-mingw32.tar.gz"
[[Zlib-build_log]]
arch = "i686"
git-tree-sha1 = "f6a2c2d33d77fcb8ec5063399b9f725807917e1d"
lazy = true
os = "windows"

    [[Zlib-build_log.download]]
    sha256 = "27d2341ca22d5be378ec3ee7424fa7138bed2765c249a5ec3f1e63737d7ad513"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-build_log-v1.3.7-i686-w64-mingw32.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "55a2f163f3a3b4fe40c2612416c126af96ddce3b"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "3433bfd590835b6a8557d6b043ae420fa7a20f4f27e4d60fe33a4d86ee7a18c5"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-x86_64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "2a199c5c9e92214590743a86853c1929820ecab7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "7703ae6077d9b96ed2e8e262907d8ad77bf78a1ab469b1c84b9950766b287d79"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-i686-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "dc948e92f03705a361f63b1bac2e3f466bbcd25d"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "9650beab8a8c9232f6d58240fab2f2198b5fb02d469964ba3aa6344c8fe61e77"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-aarch64-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d463c5f83fa8f51fb95f7a955f3605a4277895c7"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "daa59303f7985996a69ccc6f7eb3f2b867d3eb516f06ac53a541cbc47514c28c"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-armv6l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3eb23683ffce3fb1f7f9dfc68d5407a7b65aec2c"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ffeaf13dbb943435bdb44e52cdaf96fcfd00982d939d2501f3694a10ed6ab5dc"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-armv7l-linux-gnueabihf.tar.gz"
[[Zlib-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "8e430c458a7ed37f69e34ffdc42c1fafa25b4ddb"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ddbe67246a39be08e01a568186211f09b4a4c9dcca43bc5f98dc4377c35f4bc1"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-powerpc64le-linux-gnu.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dc58ba2d52556e58b0f33993aade17f3b52d246c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b3c9d48ba4f726187efa95e018339bcc53f206c73579e5524544657b14d6c7bf"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-x86_64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "0839984450965ba6ffa73dfba6c4f89af400f9fe"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "b024a354cd89eb19d45388e07220c5cc975cbff2e369c7064c2e26c5af3289e3"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-i686-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aa55d0839d816493e4b0ae09630b228c9d25d3c5"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "0ce29c027bded483d52c059d9852eae7104a4209c8739671703a17d67f9d1141"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-aarch64-linux-musl.tar.gz"
[[Zlib-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5029b32938beb51120928db52f13bdf03d3b2c9c"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "f0a1d01ba83d592d2e0beed7d93fb2fbdc0e9f2799d1399d9a303dcece3aadad"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-armv6l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ef4b990431369f5f13925d2f394e743d51fec47"
lazy = true
libc = "musl"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "aac99ec59d9ba22c3f66a605e83b245f1898c2c625a19fa629d6a43d15c62d98"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-armv7l-linux-musleabihf.tar.gz"
[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "40e50273b3b68200cb58f13d363a4a57f8d283df"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "e14a6d90ef91fc7aa257c49530321e05fe23b9a3e7a9c0a823e2a1c925cad5eb"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-x86_64-w64-mingw32.tar.gz"
[[Zlib-extract_log]]
arch = "i686"
git-tree-sha1 = "06ce62d6e47ee15e3790b527c0acec530a07c010"
lazy = true
os = "windows"

    [[Zlib-extract_log.download]]
    sha256 = "0d2ba7eed1f8b148093f38d4d743248e699b023f1995a18f4217c482ba0f213a"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.7-universe_test/Zlib-extract_log-v1.3.7-i686-w64-mingw32.tar.gz"
