[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "eef581929649c813fa85e39cb7045ffdd40c7e523f0a08cea6adcda8703cfe79"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-v1.0.16-x86_64-linux-gnu.tar.gz"

[[Zlib-build_log]]
arch = "x86_64"
git-tree-sha1 = "d71e4e22dc37e2c410c5a345c6e92af7476e407e"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-build_log.download]]
    sha256 = "5d8db18aef258469e2f034627514b381b918d2c5a043cc9081035f83221c4f71"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-build_log-v1.0.16-x86_64-linux-gnu.tar.gz"

[[Zlib-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b7877e34248619b8b7fda418ef3a91dd6f6ec2b4"
lazy = true
libc = "glibc"
os = "linux"

    [[Zlib-extract_log.download]]
    sha256 = "ad39135d6bad8d4a61867b941e1e9ee9b4c826192b4acfa49187b5f7407b9408"
    url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-extract_log-v1.0.16-x86_64-linux-gnu.tar.gz"
