name = "Zlib"
version = "1.0.12"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:989305b6e4c908d3b8a021de8d0f19dd7e214893"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:813de910d25769a6274ef43e1c3fd735315944777b16087c5c3156b7d841fce6"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-build_log-v1.0.12-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:10e758ff4f593b650cee3aa1105ee2730044244a"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:125ce01d928ab68d2750e84f6fd42d884872259fa73920e50b68bc322162fdd1"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-extract_log-v1.0.12-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:eaa4b1bc40755ff0e75c4b1e3491d8b3529211b68a4d8e2e85ca5ad4f4ced124"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.12-GCCBoostrap/Zlib-v1.0.12-x86_64-linux-gnu.tar.gz"
