name = "Zlib"
version = "1.0.15"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:7ebdb105947464dddd739b1f9d257580fe66f94e"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:de180b0627d6c427045ce2887777bca2a7a796f41ead51813492c7591ac98ac4"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-build_log-v1.0.15-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:f40b593cca31ef89c5a88284ba16437225a00934"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:748be8e2b65893a7530f85a8aae13dcec9b9aa60d65713c02c3cf1ad8fe933c5"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-extract_log-v1.0.15-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:9b640c799c6f2f66bfb4a532cd5e20b0cc57e803808faee09d485464a45abd26"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.15-GCCBoostrap/Zlib-v1.0.15-x86_64-linux-gnu.tar.gz"
