name = "Zlib"
version = "1.3.2"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:4c7e0c510f3bc918584ec8ee4141fc3c60b8b1f4"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5bef0e931e0f4f9bea0aef97b07c889f744389de4677698253abe2b58386d021"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBoostrap-aarch64-linux-gnu/Zlib-build_log-v1.3.2-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:be55cbea05aba1f8a2bdd1818fa0fa942e714ae2"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:8aebece0020877833547127753af2b68a004039e21419956349dc2304d67889d"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBoostrap-aarch64-linux-gnu/Zlib-extract_log-v1.3.2-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:d8e3f1e039b7829a8e21922cc4e2ee5e4d5d59f5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:8200c36d3dea0fbfda8453d497d2642cff5d3713ff4f3560f780b7da16a3de87"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBoostrap-aarch64-linux-gnu/Zlib-v1.3.2-aarch64-linux-gnu.tar.gz"
