name = "Zlib"
version = "1.0.16"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:d71e4e22dc37e2c410c5a345c6e92af7476e407e"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5d8db18aef258469e2f034627514b381b918d2c5a043cc9081035f83221c4f71"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-build_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b7877e34248619b8b7fda418ef3a91dd6f6ec2b4"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:ad39135d6bad8d4a61867b941e1e9ee9b4c826192b4acfa49187b5f7407b9408"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-extract_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:eef581929649c813fa85e39cb7045ffdd40c7e523f0a08cea6adcda8703cfe79"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.16-GCCBoostrap/Zlib-v1.0.16-x86_64-linux-gnu.tar.gz"
