name = "Zlib"
version = "1.3.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:0f4a7b879a5d27cbe65e582cee9fe3022f6a826e"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:eeaa14b6980152d2a39dbe356aafcb1956b19a28442197b0e2c773c65d195b48"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:64ea1bc3a9bad2559ea7369b6c880e67aebff56d"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:db29a78088a17f7e49278aa851cf30a58ffbde0d4697c4e3a46df700a4013816"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:f8326de4d0f57d10eda9caed120d46af9bb2f565cf4ba68d71934d06bf6af7d0"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
