name = "Zlib"
version = "1.0.9"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:9b014e7f6981e6c9ee55ad5969e94a1781621424"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:629c51040efa13663cd47267bf61d60af27826d026b12d48d6137a106870e1d3"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-build_log-v1.0.9-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:fcba9ac849c40b74d1cdacda4b0201c4bb97e23b"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2bbee9533414c8eb44ce2f3687fa7c220a3146d9635d8f543e4ddce7c16edf41"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-extract_log-v1.0.9-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3607f2b4b752875d96fbc6a6f9bfb69a469ee4a885c2392558af45c40e964c7a"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.9-GCCBoostrap/Zlib-v1.0.9-x86_64-linux-gnu.tar.gz"
