name = "Zlib"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "1.3.1"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:62bb012162f7f8dc399f865fc0ec57c8a6a5f79a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:8da47084960f620f45037a0c3cfabb43ee658bf629009ddabf08afea486123f6"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:73ab90d01bf7b5b7983a851d0bd31be6394da5dd"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:16de5ba0d4214467e2d5b9e794c694002723a1e71c805702860deec1c48123e1"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:d8e3f1e039b7829a8e21922cc4e2ee5e4d5d59f5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:92ff6b714531d88c25f9be220e1cc5e2fab9c851f04229b0cc1ca0f2d91a3f83"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-v1.0.0-aarch64-linux-gnu.tar.gz"
