name = "Zlib"
version = "1.3.3"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:d04ea1f0465e21eff30c2baa191e3b202d3cbbe7"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:cbbec43447909de6965887d9287015107404f1961fbaabb1957753fabcc58237"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-GCCBootstrap-x86_64-linux-gnu/Zlib-build_log-v1.3.3-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:fb7372f73a41bc37d3d0ca9f56b30f36b5fbf356"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d2170fd9446b37aa4627367cbd4d815e14c5e8ed9bd75c695607741ac66a2a76"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-GCCBootstrap-x86_64-linux-gnu/Zlib-extract_log-v1.3.3-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5de3954000147f540c67f10ece7d1ca8896bc780c414ecfc0714701242b5e82a"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.3-GCCBootstrap-x86_64-linux-gnu/Zlib-v1.3.3-x86_64-linux-gnu.tar.gz"
