name = "Zlib"
version = "1.0.11"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3b5647edc1f8fe4329f1f5750e83c547376b2070"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ebbed224948f91faf30884944bb98e64884cbcf7f151a9d9101f82d43ab8f746"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-build_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c17bd6b8ea8786abb8135ec6026ffd0d0e48654b"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d367c816f3fb8fe0575613933a503b159f640a4034ee602013a9c80e97baef38"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-extract_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:728eb68d2a8a6dc2251050669fd499ffec69056566cbac8132d6d3ffe341a986"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.11-GCCBoostrap/Zlib-v1.0.11-x86_64-linux-gnu.tar.gz"
