name = "Zlib"
version = "1.0.14"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:506f32bf7927376ae6b313232aa4313f645bb4e6"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:47c620d9b5af6e11673e46a32a0a27e69b700755bdf8c9558410c6aabdec8e15"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-build_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:59a00b19e1e6ee4a7f1288dfbd6ab59612ff4746"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e3d4afc9d7bd0dd594649e0cf483cc76977c33e6f40cec202b6be5f9fe80a4b9"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-extract_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:6dbb9f79208a887a1848de4982c963572a1b9b33e9a59bfdae7b1bd260381b43"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.14-GCCBoostrap/Zlib-v1.0.14-x86_64-linux-gnu.tar.gz"
