name = "Zlib"
version = "1.3.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "Zlib"
platform = "x86_64-linux-gnu"
deps = []
lazy = "false"
src_version = "1.3.1"

    [[builds.licenses]]
    license_text = """Copyright notice:\n\n (C) 1995-2022 Jean-loup Gailly and Mark Adler\n\n  This software is provided 'as-is', without any express or implied\n  warranty.  In no event will the authors be held liable for any damages\n  arising from the use of this software.\n\n  Permission is granted to anyone to use this software for any purpose,\n  including commercial applications, and to alter it and redistribute it\n  freely, subject to the following restrictions:\n\n  1. The origin of this software must not be misrepresented; you must not\n     claim that you wrote the original software. If you use this software\n     in a product, an acknowledgment in the product documentation would be\n     appreciated but is not required.\n  2. Altered source versions must be plainly marked as such, and must not be\n     misrepresented as being the original software.\n  3. This notice may not be removed or altered from any source distribution.\n\n  Jean-loup Gailly        Mark Adler\n  jloup@gzip.org          madler@alumni.caltech.edu\n"""
    filename = "LICENSE"
    license_type = "Zlib"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:77d2cd7d2192c013206ad54d43c6625146492c36"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:204eb0ec17a27a446a708d52cf4e47ac3818be54017b06eb5428699f92a9350a"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:f52a9eb3ffc36253214fba8db8619a7a36a07522"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:6c6e1723869a858950422c66ab73cb67afb719a1c29eaeba3ef0f1e0f21bc884"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:881524c8f7463c67455e3b21814d751b8dda7697"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:64220aa7398aa71d48d1fc7e4d7ad3b0453181ab9f3c94381187dd787be5a06a"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
