name = "Zlib"
version = "1.3.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f6216bd61d02d4c7a5c04f8c70ce7370cc39f997"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:cf25b431d9d709c6684d44adf03692f4021fe5b363a5354d2e90c8ec8500de0f"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-build_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:6233bff54fcd31e5c3c10f66756f856417cf8eec"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:1ac58823e2357eb2e80690f7abbe944144bd6388ab24f78b6b538e17f2668ad8"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-extract_log-v1.3.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:abab3ad4534638cb1e92bcc7a47bf95f822b2f551f7b06e9905b698e8b432e95"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.3.2/Zlib-v1.3.2-x86_64-linux-gnu.tar.gz"
