name = "Zlib"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "1.3.1"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:62bb012162f7f8dc399f865fc0ec57c8a6a5f79a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:25f0eafaf3a4011c63dde3818c3c9544dbcc1951c3bd8df96dddef64e65f2e0a"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:73ab90d01bf7b5b7983a851d0bd31be6394da5dd"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d62b94b841907801ad2569a54340a8c2e25896425a91bb5d2941eef7b049cdd6"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:d8e3f1e039b7829a8e21922cc4e2ee5e4d5d59f5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5752cb95c2cc12e787a57c46b9571963d0f968511341ea87bd1c38820d8a786d"
        url = "https://github.com/staticfloat/releases/download/v1.0.0/Zlib-v1.0.0-aarch64-linux-gnu.tar.gz"
