name = "Zlib"
version = "1.0.17"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Zlib"
lazy = "false"
src_version = "1.3.1"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:b3392fe005d65f97cf3fe81df0a85f1a76959ae6"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6f5dc32f66dd7e71620acca0d1b1ee5e5771b40314a37a5db3fe17bd76e8f046"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-build_log-v1.0.17-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:569b598bc86113c278dbd4584ac9635fa9edcf55"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:216c6d40d93b982c6b3b637a2a88727f050ee3df72543fc72f9bbf5573944078"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-extract_log-v1.0.17-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libz"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libz.so.1"
    type = "library"
    path = "lib/libz.so.1.3.1"

    [[builds.sources]]
    treehash = "sha1:51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf"
    url = "https://github.com/madler/zlib.git"

    [builds.artifact]
    treehash = "sha1:0cfb0a3d5ac3ebbe834bab0060f3f0831abbd379"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5483b730f46e61ac3bac969bbda9944738cbe5eae85558b643901ec9ee7c7fca"
        url = "https://github.com/staticfloat/Zlib_jll.jl/releases/download/v1.0.17-GCCBoostrap/Zlib-v1.0.17-x86_64-linux-gnu.tar.gz"
